### ISSUE TITLE
Try becoming API compatible with the common stuff in CALFEM

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#1]
##### Springs

- [x] `spring1e`
- [x] `spring1s`

##### Bars
- [x] `bar2e`
- [x] `bar2s`
- [x] `bar2g`

##### Solids (TODO: plane stress)
- [x] `plante`
- [x] `plants`
- [x] `plantf`

-------------

- [x] `plani4e`
- [x] `plani4s`
- [x] `plani4f`

---------

- [x] `plani8e`
- [x] `plani8s`
- [x] `plani8f`

---------------

- [x] `soli8e`
- [x] `soli8s`
- [x] `soli8f`

##### Heat flow
- [x] `flw2te`
- [x] `flw2ts`

-----------------

- [x] `flw2i8e`
- [x] `flw2i8s`

-----------------

- [x] `flw2i4e`
- [x] `flw2i4s`

---------------

- [x] `flw2i8e`
- [x] `flw2i8s`

----------

### Materials
- [x] `hooke`

### Utilities

- [x] `assem`
- [x] `solveq`
- [x] `extract`
- [x] `statcon`
- [x] `coordxtr`

### Graphics

- [x] `eldraw2`
- [x] `eldisp2`

##### Bars

- [ ] `bar3e`
- [ ] `bar3s`

##### Beams

- [ ] `beam2e`
- [ ] `beam2s`

---------

- [ ] `beam2t`
- [ ] `beam2ts`

---------

- [ ] `beam2w`
- [ ] `beam2ws`

---------

- [ ] `beam2g`
- [ ] `beam2gs`

---------

- [ ] `beam2d`
- [ ] `beam2ds`

--------

- [ ] `beam3e`
- [ ] `beam3s`

###  Materials
- [ ] `mises`
- [ ] `dmises`

###  Utilities

- [ ] `eigen`
- [ ] `insert`

###  Grahpics

- [ ] `fill`
- [ ] `eldia2`
- [ ] `elflux2`
- [ ] `elprinc2`
- [ ] `scalfact2`
- [ ] `pltscalb2`

**Comment by KristofferC** [comment]
Kan vi skita i `planqe` och dom? Enda meningen med dom är väl om det är någon student som vill kolla på koden och inte lärt sig om isoparametriska element än.

**Comment by JimBrouzoulis** [comment]
Vilka är de? Jag kan inte namnen.

**Comment by KristofferC** [comment]
Rektangulära element samt "quadraterial" elements som inte använder gaussintegrering.

**Comment by JimBrouzoulis** [comment]
Jaha, det är sånna där "Meloshelement" som måste ha sidorna paralella med koordinataxlarna.
Ja, fuck them!
________________________________
