### ISSUE TITLE
Useful grid functionality

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#102]
Get nodes from elementset / boundaryset.

**Comment by KristofferC** [comment]
Also. Being able to call `reinit(values,  grid,  cellindex)`,  `reinit(boundary valves,  grid,  boubdaryindex)`

I sort of like "face" or "surface"  more than boundary fwiw.

**Comment by KristofferC** [comment]
Also, calling grid generators with function spaces would be useful. (I am starting to like the term interpolation spaces more and more...)

**Comment by fredrikekre** [comment]
`FaceValues`

**Comment by fredrikekre** [comment]
`InterpolationSpace`

**Comment by fredrikekre** [comment]
Yea, I felt it was weird from the start actually. Function spaces are `U` and `U^0`

**Comment by KristofferC** [comment]
Deal.II calls them Finite element spaces: https://dealii.org/8.4.0/doxygen/deal.II/group__fe.html

**Comment by KristofferC** [comment]
Could just be `Interpolation` as well.. hmm

**Comment by fredrikekre** [comment]
I like that!

**Comment by KristofferC** [comment]
`getcells` and company, should they be plural or singular, Base uses for example `getindex` etc.

**Comment by KristofferC** [comment]
Sometimes you want the actual nodes and sometimes you just want their number. It would be good to have some convention to distinguish between these two cases.

**Comment by fredrikekre** [comment]
+1 for `Interpolation` and +1 for `FaceValues`.

`getnode` and `getnodeid` maybe? I dont really care if we use plural or not, lets at least be consistent!

**Comment by KristofferC** [comment]
This is done / obsolete.
