### ISSUE TITLE
Stuff to fix

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/JuAFEM.jl#131]
Umbrella issue to track things to tweak:

- [ ] some way for a node to know it is on the boundary. Useful for something like this: `addnodeset!(grid, "all nodes on boundary", onboundary)`
     Edit: We can do this with dispatch on `onboundary`
- [ ] currently `push!` is used to add fields to a dofhandler, while for grid we have `addnodeset`/`addcellset`. Should we have `addfield!()` to be more consistent? (and for BC we simply have `add!`)
- [x] ~ export some more stuff: `free_dofs`, `dirichlet_dofs` ? ~
- [x] ~ `reduce(K::Matrix, dbc)` that reduces the matrix ~

**Comment by KristofferC** [comment]
For point 4, isn't it enough to export `free_dofs`? Do we really need a function that does `K[free_dofs(dbc), free_dofs(dbc)]`.

**Comment by fredrikekre** [comment]
either or

**Comment by KristofferC** [comment]
`constrain_nodeset`, `constrain_faceset` etc?

**Comment by fredrikekre** [comment]
for what?

**Comment by KristofferC** [comment]
For dirichlet boundary conditions on different type of sets.

**Comment by fredrikekre** [comment]
instead of `add!(dbc, ...)` ?

**Comment by KristofferC** [comment]
Yeah, that's what I thought.. I dunno.

**Comment by KristofferC** [comment]
We should consider if the new assembler really should wrap `K` and `f` or if the call should just be `assemble(assembler, K, Ke, f, fe, celldofs)` or something. It hides a bit what is happening when you wrap it but you need fewer arguments when you later use it. Thoughts?

**Comment by fredrikekre** [comment]
Does not really matter, all those variables are typically in scope anyway so no additional argument passing if we don't wrap it

**Comment by fredrikekre** [comment]
the I,J,V version is kind of a wrapper though

**Comment by fredrikekre** [comment]
This feels kind of awkward
```julia
K = create_sparsity_pattern()
assembler = start_assemble(K)

# lots of code here

assemble!(assembler, ke, cell_dofs)
# here K is updated...
```

**Comment by fredrikekre** [comment]
`norm(g[JuAFEM.free_dofs(MP.dbc)])`

**Comment by fredrikekre** [comment]
cache edof in CellIterator jus tlike we cache the coordinates?

**Comment by KristofferC** [comment]
I like it.
