### ISSUE TITLE
DofHandler does't account for higher order basis functions

### ISSUE THREAD

**Issue by juan42** [KristofferC/JuAFEM.jl#153]
In the following setting
```
dim = 2
grid = generate_grid(Quadrilateral, (1, 1))
ip = Lagrange{dim, RefCube, 1}()
qr = QuadratureRule{dim, RefCube}(2)
cellvalues = CellScalarValues(qr, ip)
```
results in
```
JuAFEM.CellScalarValues{2,Float64,JuAFEM.RefCube} with 9 shape functions and 4 quadrature points
```
so i would expect the DofHandler to produce a 9x9 sparsity pattern, but it doesn't have the information for recognizing that.

**Comment by KristofferC** [comment]
I think you meant `ip = Lagrange{dim, RefCube, 2}()`

Unfortunately, the DofHandler currently only works with isoparametric elements so you need to use `QuadraticQuadrilatera` when creating the `grid`:

```
const dim = 2
grid = generate_grid(QuadraticQuadrilateral, (1, 1))
ip = Lagrange{dim, RefCube, 2}()
qr = QuadratureRule{dim, RefCube}(2)
cellvalues = CellScalarValues(qr, ip)
dh = DofHandler(grid)
push!(dh, :u, 1)
close!(dh)
dh
```

gives:

```
DofHandler
  Fields:
    u dim: 1
  Total dofs: 9
  Dofs per cell: 9
```

**Comment by juan42** [comment]
Bummer. Is an implementation planned or do you know any good resources where to look how this is implemented intelligently?

**Comment by KristofferC** [comment]
Is there a problem using higher order elements in the `grid`? 

In theory, implementing it is not that hard. Just loop over all elements and add degrees of freedom where the interpolation space says they are needed :).
In practice, it is quite tricky because you need to make sure to add dofs in the correct "order" so that the orientation between elements is consistent etc.

 I started on it here: https://github.com/KristofferC/JuAFEM.jl/pull/138 but haven't had time to revisit it.

**Comment by edljk** [comment]
Nice PR !
The functions
```
get_dof_local_coordinates(::Lagrange{dim, RefTetrahedron, order})
```
seem to be missing to extend non isoparametric elements to Tetrahedron case ?

**Comment by fredrikekre** [comment]
```julia
const dim = 2
grid = generate_grid(Quadrilateral, (1, 1))
ip = Lagrange{dim, RefCube, 2}()
qr = QuadratureRule{dim, RefCube}(2)
cellvalues = CellScalarValues(qr, ip)
dh = DofHandler(grid)
push!(dh, :u, ip, 1)
close!(dh)
dh
```
with output:
```
DofHandler
  Fields:
    :u interpolation: JuAFEM.Lagrange{2,JuAFEM.RefCube,2}(), dim: 1
  Dofs per cell: 9
  Total dofs: 9
```
:tada:
