### ISSUE TITLE
Support adding boundary conditions on specific nodes

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/JuAFEM.jl#166]
After #159 we add boundary conditions on facesets. It is sometimes needed to lock individual nodes, to hinder e.g. rotation. We should have a way to do this.

**Comment by mohamed82008** [comment]
May I ask how you think this should be done? I am currently still using the JuAFEM before #159 mainly because of this issue.

**Comment by mohamed82008** [comment]
Using a face index of `(-1, global_node_idx)` to represent solo nodes is one option/hack that doesn't change the structs used.

**Comment by mohamed82008** [comment]
Alternatively, one can remove this field `dbcs::Vector{DirichletBoundaryCondition}` from the `DirichletBoundaryConditions` struct and then parameterize `DirichletBoundaryCondition` to have one defined on faces and one defined on nodes. I personally can't find any use of `dbcs.dbcs` in this package but perhaps one might expect to have access to the individual boundary conditions from a `DirichletBoundaryConditions` instance in which case, we can go the opposite way and have 2 vectors one for `Vector{DirichletBoundaryCondition{:faces}}` and one `Vector{DirichletBoundaryCondition{:nodes}}`.

**Comment by mohamed82008** [comment]
I will go ahead with the `Dirichlet{:faces}` and `Dirichlet{:nodes}` solution in a PR.

**Comment by mohamed82008** [comment]
When applying the boundary conditions, the faces bcs are applied first followed by the nodes, which means that some may be overwritten. For example a bunch of faces can have some boundary condition but a few select nodes on the faces can have another boundary condition. We can discuss it further once the PR is made.

**Comment by mohamed82008** [comment]
https://github.com/KristofferC/JuAFEM.jl/pull/194
