### ISSUE TITLE
colon error in steprange

### ISSUE THREAD

**Issue by louisponet** [KristofferC/JuAFEM.jl#184]
Not sure if this is a bug in julia or a syntax error in the package. Anyway the following code confuses `julia` steprange and colon from ternary operator. 

Code to reproduce the error:
```
using JuAFEM
grid = generate_grid(Tetrahedron, (20, 20, 20))
dh = DofHandler(grid)
ip = Lagrange{3, RefTetrahedron, 2}()

push!(dh, :u, 1, ip)
close!(dh)
```
line of the error:

https://github.com/KristofferC/JuAFEM.jl/blob/a007e3d0a650954472fe059150088abc69d567c6/src/Dofs/DofHandler.jl#L162

Code to fix error:
`for edgedof in (dir == olddir ? (1:interpolation_info.nedgedofs) : (interpolation_info.nedgedofs:-1:1))`

Cheers!

**Comment by fredrikekre** [comment]
Yea, there should be parentheses around like you say. Care to open a PR with the fix?

**Comment by louisponet** [comment]
Done!

**Comment by fredrikekre** [comment]
#185
