### ISSUE TITLE
Bug in addcellset!

### ISSUE THREAD

**Issue by mohamed82008** [KristofferC/JuAFEM.jl#189]
https://github.com/KristofferC/JuAFEM.jl/blob/7f5ae3f1e614f6213c8e7b8216d43a96172739c6/src/Grid/grid.jl#L124

I believe the way the `all` keyword is implemented is not correct here. This is because if `all` is false, then `pass` is false and there is no way for it to become `true`, so no cells will be added. Initializing `pass` to `true` would probably fix this, PR in the making.

**Comment by mohamed82008** [comment]
On second thought, my proposed fix isn't correct since if `all` is `false` and `pass` is initialized to `true`, then there is no way for `pass` to become `false` so all cells will be added.

**Comment by mohamed82008** [comment]
I believe the implementation in the original PR is correct and is the one I use on my branch https://github.com/KristofferC/JuAFEM.jl/pull/162.

**Comment by mohamed82008** [comment]
Another simple fix was used in the above PR.

**Comment by fredrikekre** [comment]
#190
