### ISSUE TITLE
generate_grid(Tetrahedron) results in bad grid 

### ISSUE THREAD

**Issue by natschil** [KristofferC/JuAFEM.jl#210]
As far as I can tell the current generate_grid() for Tetrahedral elements in 3D results in discontinuous "hat" functions.

To see this, notice that for every hexahedron the line (1,0,0) to (1,1,1) passes through a face and separates two elements. But for the adjacent hexahedron, this line is within an element.  See also http://www.baumanneduard.ch/Splitting%20a%20cube%20in%20tetrahedras2.htm (which is cited in generate_grid which does a rotated version of #13): if you look at the image of #13, you'll see that the lines on adjacent cubes don't fit together.

**Comment by haampie** [comment]
I didn't get this issue without a figure, so here's a screen from paraview showing the problem:

![cube](https://user-images.githubusercontent.com/194764/39912580-da4cc6f8-5507-11e8-9c2f-75859db468e9.png)

If you look at the back faces of the closest cube, you see that the faces don't line up -- there's a cross in the square.

**Comment by KristofferC** [comment]
https://julialang.slack.com/files/U67D54KS8/FALLSRQ81/screen_shot_2018-05-09_at_23.57.58.png

Also

**Comment by louisponet** [comment]
For educational purposes, can I ask what issues this results in? Or could result in ?
