### ISSUE TITLE
heat_equation.jl example confusing markdown and julia comments?

### ISSUE THREAD

**Issue by anriseth** [KristofferC/JuAFEM.jl#214]
The function `doassemble` in the `heat_equation.jl` example has many julia comments in the code, but uses `#` rather than `##`, so the code gets split up in the markdown presentation:
http://kristofferc.github.io/JuAFEM.jl/latest/examples/generated/heat_equation.html

I'm just checking whether that's the intention, or due to the change in how comments are processed in Literate.jl

**Comment by fredrikekre** [comment]
Nah, that is very much intended, I even patched Documenter to make it possible (https://github.com/JuliaDocs/Documenter.jl/pull/695).

**Comment by fredrikekre** [comment]
Tried to mimic e.g. https://www.dealii.org/8.4.0/doxygen/deal.II/step_3.html which has the same setup.

**Comment by anriseth** [comment]
Okay, fair enough:)
