### ISSUE TITLE
Include JuAFEM in a package via REQUIRE

### ISSUE THREAD

**Issue by dkarrasch** [KristofferC/JuAFEM.jl#221]
Once the JuAFEM upgrade to Julia 0.7 is through, how would one include it in a non-registered package that uses REQUIRE? Just mentioning JuAFEM there seems to give an error.

**Comment by fredrikekre** [comment]
This is because it is not a registered package. In Julia 0.7 you can add a package with an URL.

**Comment by dkarrasch** [comment]
Sorry, must have been misleading. I think I was able to `add` JuAFEM in Julia 0.7, but failed to include it in a package of mine. I currently cannot reproduce the error message because now other packages that our package depends on produce issues with the packages they depend on. I guess I'll need to wait a bit until the upstream packages are all updated. Other than that, should it be sufficient to have a line `JuAFEM` in my REQUIRE, i.e., without any additional information like uuid etc.?

**Comment by fredrikekre** [comment]
Right, you can only add package that are registered in METADATA to REQUIRE. In 0.7 you will not  have a REQUIRE file so this should hopefully not be a problem then.

**Comment by dkarrasch** [comment]
I fixed it by adding a `Project.toml` file.
