### ISSUE TITLE
Jacobian Determinant Abs

### ISSUE THREAD

**Issue by PaulMatlashewski** [KristofferC/JuAFEM.jl#223]
Is there a reason for throwing an error for negative Jacobian determinants instead of taking the absolute value? I've always seen the change of variables formula with an absolute value, but I could be missing something subtle where the orientation matters.

https://github.com/KristofferC/JuAFEM.jl/blob/efa2eff1eef971eeb077ef12cd4933c02a62a2a3/src/FEValues/cell_values.jl#L156-L157

**Comment by KristofferC** [comment]
It matters for the direction of the normals to the surface of the element. So if your element is "inside out" the normal will point into the element.

**Comment by PaulMatlashewski** [comment]
Okay, I see. But I don't think this should always be an error, should it? In the Laplace equation, for example, we only really need the absolute value of the detJ to map from the reference triangle.

I'm getting this error because the mesh I'm reading seems to be inconsistent with the direction it's numbering vertices in a triangle.

**Comment by KristofferC** [comment]
Negative determinant can also occur if higher order elements are heavily distorted so just looking at the absolute value could hide bugs.

It seems easiest to just enforce an orientation and if some other mesh has another convention, just swap the node order.

**Comment by PaulMatlashewski** [comment]
Okay cool. I'm definitely not a FEM expert so it's good to know these things. That sounds like the best way forward. Thanks!
