### ISSUE TITLE
Have a version comatible with Julia 0.6?

### ISSUE THREAD

**Issue by dkarrasch** [KristofferC/JuAFEM.jl#224]
Somehow, the Julia 0.6 package manager doesn't seem to get that the latest master is made for Julia 0.7/1.0 only. Is it possible to have a tagged version that works with Julia 0.6? The complaint is that Julia doesn't know the library `LinearAlgebra`.

**Comment by fredrikekre** [comment]
You can (manually) checkout commit efa2eff1eef971eeb077ef12cd4933c02a62a2a3 :stuck_out_tongue:

**Comment by fredrikekre** [comment]
I meant from the command line (`git checkout efa2eff`). I created a branch, `release-0.3` that will work on 0.6. You should now be able to `Pkg.checkout("JuAFEM", "release-0.3")`.

**Comment by dkarrasch** [comment]
I had to remove, add, and checkout, but it can be `using`ed without complaints. Fantastic, thanks once more.

**Comment by fredrikekre** [comment]
Ah ok, I added a note about this in the README: #225
