### ISSUE TITLE
A preliminary question about calling functions of JuAFEM 

### ISSUE THREAD

**Issue by yoczhang** [KristofferC/JuAFEM.jl#236]
Hi everyone,

I am a new learner of Julia and JuAFEM. I want to ask a preliminary question about calling the JuAFEM functions: In the Julia-REPL, I run some functions like that
```julia-repl
julia> using JuAFEM, SparseArrays

julia> grid = generate_grid(Quadrilateral, (20, 20));

julia> dim = 2;

julia> ip = Lagrange{dim, RefCube, 1}();
```
I want to check the functions in **interpolations.jl**, first I run the **getnbasefunctions()** function successfully
```julia-repl
julia> getnbasefunctions(ip)
4
```
but the **getdim()** function  failed
```julia-repl
julia> getdim(ip)
ERROR: UndefVarError: getdim not defined
Stacktrace:
 [1] top-level scope at none:0
```
the calling of **value()** function is also failed.

Actually,  **getnbasefunctions(), getdim(), value()** are in the same file **interpolations.jl**, and **getnbasefunctions()** is exported by the **exports.jl**. 

But in the **cell_values.jl** I find that 
```julia
@assert getdim(func_interpol) == getdim(geom_interpol)
...
ξ -> value(geom_interpol, basefunc, ξ)
```

I'm wondering to know that why the functions in **cell_values.jl** can call the functions in **interpolations.jl** which are not exported by the **exports.jl**?

**Comment by fredrikekre** [comment]
> I am a new learner of Julia and JuAFEM.

Welcome!

What is in the `exports.jl` file is what is available after calling `using JuAFEM`. The other functions are internal (but you can still call them as `JuAFEM.getdim(...)` for example), so they can be used inside the `JuAFEM` module without any problem. Does that answer your questions?

**Comment by yoczhang** [comment]
Thank you,
> so they can be used inside the `JuAFEM` module
That means (such as) heat_equation.jl is 'outside' of  `JuAFEM` module, right?

**Comment by fredrikekre** [comment]
Yea.

**Comment by yoczhang** [comment]
ok, I got it. Thank you very much!
