### ISSUE TITLE
ERROR: LoadError: UndefVarError: assemble not defined

### ISSUE THREAD

**Issue by OVGULIU** [KristofferC/JuAFEM.jl#250]
in hyperelastic model, error:
`
ERROR: LoadError: UndefVarError: assemble not defined`

Best

**Comment by fredrikekre** [comment]
Thanks for the report. I am guessing you are talking about this https://github.com/KristofferC/JuAFEM.jl/blob/master/examples/hyperelasticity.ipynb notebook? Looks like we have not updated that one for Julia 1.0 syntax.

**Comment by KristofferC** [comment]
Closed by https://github.com/KristofferC/JuAFEM.jl/pull/256?

**Comment by fredrikekre** [comment]
Yes: http://kristofferc.github.io/JuAFEM.jl/dev/examples/generated/hyperelasticity/
