### ISSUE TITLE
reinit!(cellvalues, cell) only works for certain degrees

### ISSUE THREAD

**Issue by jw3126** [KristofferC/JuAFEM.jl#265]
The following throws an assertion error:
```julia
using JuAFEM

grid = generate_grid(QuadraticLine, (2,))
dim = 1
deg = 1 # deg = 2 is the only value that does not throw
ip = Lagrange{dim, RefCube, deg}()
qr = QuadratureRule{dim, RefCube}(deg+1)
dh = DofHandler(grid)
push!(dh, :u, 1, ip)
close!(dh);
cell = first(CellIterator(dh))
cv = CellScalarValues(qr, ip)
reinit!(cv, cell)
```
```
AssertionError: length(x) == n_geom_basefuncs
```

**Comment by fredrikekre** [comment]
You (currently) have to match the geometric interpolation with the order of the mesh. If you want a quadratic mesh with a linear field you can do this:
```julia
using JuAFEM

grid = generate_grid(QuadraticLine, (2,))
ip_fe = Lagrange{1, RefCube, 1}() # interpolation for the function
ip_geo = Lagrange{1, RefCube, 2}() # interpolation for the geometry
qr = QuadratureRule{1, RefCube}(2)

# Specify both function + geometry interpolation
cv = CellScalarValues(qr, ip_fe, ip_geo)

dh = DofHandler(grid)
push!(dh, :u, 1, ip_fe) # function interpolation
close!(dh)

cell = first(CellIterator(dh))
reinit!(cv, cell)
```

**Comment by jw3126** [comment]
Ok I see. So possible fixes that come to my mind would be:
1. Delete this constructor `CellScalarValues(qr, ip_fe)`
2. Throw a better error message in `reinit!`

To make 1. less inconvenient, there could be a factory function
`cv = create_cell_values(qr, dh, :u)`
What do you think?

**Comment by fredrikekre** [comment]
> 1. Delete this constructor CellScalarValues(qr, ip_fe)

This is very common though, since you often use isoparametric elements so I think this should stay.

> 2. Throw a better error message in reinit!

Yea, we can do that. Probably should not have used `@assert` in the first place.

**Comment by jw3126** [comment]
I am not very familiar with the "higher order" cells like `QuadraticLine`. Is it the case, that for each subtype of `Cell` there is at most one matching `ip_geo`? And we could in principle compute that `ip_geo` from the `Cell` instance and not make it part of e.g. `CellScalarValues`?
