### ISSUE TITLE
Minisymposium at JuliaCon ?

### ISSUE THREAD

**Issue by j-fu** [KristofferC/JuAFEM.jl#273]
Hi, I am Jürgen Fuhrmann from Weierstrass Institute Berlin, and the author of VoronoiFVM.jl

I would like to propose a minisymposium for JuliaCon which "collects" people interested in PDEs.
Below is a draft of a proposal. Would you like to participate ?

**Julia for Partial Differential Equations**

Simulations based on models described with partial differential equations (PDEs) are demanding with respect to probelem sizes, memory access patterns, and the high diversity of models and discretization approaches.

Julia with its capabilities with respect to near optimal scalar performance, build-in multithreading, multiprocessing and packages for GPU computing in combination with its generic programming facilities provides a new opportunity to implement well performing and easy to uses packages for PDE solution.

On the other hand due to the juvenile age of the language and the package universe, the full potential of Julia with respect to this problem class has not been reached yet.

The minisymposium contributors present several Julia packages connected with the solution of partial differential equations and systems thereof which might appeal to a broader public.

The minisymposium intends to conclude with a discussion of possible developments of features and packages for PDE simulations which would help Julia to become one of the primary choices for researchers and engineers interested in PDE simulations.

Possible schedule:

- 3-5 talks  30-20min each
- Discussion 30-20min

**Comment by KristofferC** [comment]
Sure, we could have a presentation about JuAFEM.jl.

**Comment by j-fu** [comment]
Hi, I submitted the minisymposium proposal:
https://pretalx.com/juliacon2020/talk/review/SHYAMYTZKXLAGU983ST8WDJEVYUAT3FH

As for the Virus, the organizers work on plan B to have the conference online-only.

**Comment by j-fu** [comment]
Hi,

the JuliaCon minisymposium on PDE solution in Julia has beem accepted.  It will take place on Friday, 2020-07-31 18:00-19:30 UTC.

Unfortunately, during the last weeks I was absorbed by another project, so this information comes to you very late. Please accept my apologies for this situation.

The conference will be on-line, and it is expected that the talks are pre-recoded.  I managed to appoint an upload time for the talks 
early next week, preferably by Monday, July 20. During the talks, participants are expected to be presend on the conference chat in discord.

For recording, the organizers recommend OBS or zoom.

During the application period, six package authors (including myself) showed their interest in participating, and I envision to just give all of them the same opportunity to present their work.

That would be a 15min talk for each participant. We might see cancellations, moreover there will be another talk on GridAP already, so the number might reduce to 5 or 4, and the available time per talk increas to 18 -22 min.  I will keep you updated on this.

Here are some thoughts on what I think should be in a talk.

- Which problem class does your package handle best ?
- How users are supposed to describe their problems ? Describe/demonstrate the API of your package.
- Discuss specifics of your method/package.
- How does it integrate with other packages (plotting, meshing, diffeq etc.)
- Which features/packages you would like to see in Julia ?

I would welcome further ideas for the organization of the minisymposium.

Please let me know if you are still in and willing to contribute.

**Comment by mohamed82008** [comment]
Who were the six package authors?

**Comment by j-fu** [comment]
Hi
its @PetrKryslUCSD, @krcools, myself. Then @fverdugo who seems to have an extra talk, and @dlfivefifty who for personal reasons will not be able to upload a recorded talk in the next couple of days. And of course @KristofferC.

**Comment by j-fu** [comment]
Petr talked to @chakravala, he seems to be interested, too.

**Comment by KristofferC** [comment]
I'm going on vacation tomorrow and will have difficulty recording anything for that date. I kind of forgot about this and the confirmation is indeed a little bit late. I'm not sure if anyone else here would be up to make a talk, cc @fredrikekre

**Comment by chakravala** [comment]
Indeed, I might be interested in the mini-symposium, but wasn't planning to before Petr asked me about it today.

It is indeed a bit inconvenient of a date on such a short notice, having any amount of extra time would be good.

I will try to put something together by Monday, but would prefer having some extra time for making revisions.

**Comment by j-fu** [comment]
First, thank you very much for being ready to do this! 
The organizers (Avik Sengupta) talked about "early next week". I updated them that we would like to have a bit more time, perhaps Tuesday or Wednesday noon.

Will keep you updated on the response.

**Comment by j-fu** [comment]
> I'm going on vacation tomorrow and will have difficulty recording anything for that date. I kind of forgot about this and the confirmation is indeed a little bit late. I'm not sure if anyone else here would be up to make a talk, cc @fredrikekre

I understand, and the situation indeed is a bit sad. I still would be happy to include a contribution from others knowing this package.

**Comment by krcools** [comment]
What is the preferred file format for presentations?

**Comment by PetrKryslUCSD** [comment]
Juergen mentioned video recordings above. I am not familiar with OBS, and I believe the zoom recording is MP4.

The upload is then done at https://juliacon.org/2020/upload/

**Comment by chakravala** [comment]
Hi folks, I don't think I will submit a presentation after all.

I don't owe the Julia community a free presentation about my work.

I would be interested in collaborating with any of you in the future, but don't wish to participate in JuliaCon 2020

If you're curious about my work, you can find out about it from other organizations, like AIAA or AACA

If my work in finite elements interests you, you are also welcome to contact me privately or open an issue on my repositories.

**Comment by j-fu** [comment]
Hi, of  course it is  you who decides about this. Would have loved to get a focused introduction about your work, but then I will look it up by myself. May be we meet again at Triangulate.jl ;-)

**Comment by chakravala** [comment]
Well, ultimately you can blame people like @StefanKarpinski and @stevengj for me canceling my invited JuliaCon talk.

They make me feel unwelcome in the Julia community with their public posts slandering me on the Julia discourse.

If they decide to resolve the conflict to make me feel welcome at JuliaCon, then I might reconsider submitting it.

**Comment by j-fu** [comment]
Ok I am not familiar with this conflict, so not taking sides here. Personally by default I assume best intentions from all. Wish you and the community this will be resolved some day.

**Comment by KristofferC** [comment]
It's unfortunate you decided to cancel. However, let's keep this specific discussion away from this issue since I feel it can easily be  bit too much of a distraction.

**Comment by krcools** [comment]
I submitted as 'BEAST.jl - Minisymposium on Partial Differential Equations'. Please let me know if you require any amendments. Thank you again for inviting me! I am looking forward to see the other contributions in this mini-symposium and beyond!

**Comment by chakravala** [comment]
Submitted 'Grassmann.jl - Minisymposium on Partial Differential Equations' mp4 but I'm not officially registered, so I don't know if it is to late to get approved or not.

**Comment by j-fu** [comment]
How long is the video?

**Comment by j-fu** [comment]
Anyway thanks for submitting - will try to get it approved with the organizers.

**Comment by chakravala** [comment]
The length is 17:24, although I could make it both longer or shorter or make revisions.

If it's too much trouble to get approved, don't worry about it, thanks for trying!

**Comment by j-fu** [comment]
It's approved, so thanks again for submitting.

The length is alright  - would be more trouble to change things now.
