### ISSUE TITLE
Petition to remove the first row in EDOF

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/JuAFEM.jl#37]
This is a petition to remove the unnecessary first row of the _edof_ matrix. It is never used and makes life harder than it needs to be.

Advantages:
- Everywhere the _edof_ matrix is used, the first row is removed
- Simplifies coding since, you can write `edof(:,i)` instead of `edof(2:end,i)`
- The code looks nicer, i.e `edof(:,i)` looks much better than `edof(2:end,i)`

Disadvantages:
- None (except some rewriting of code

Please vote [here!](http://strawpoll.me/6706409)

> Nature is pleased with simplicity. And nature is no dummy
― Isaac New

**Comment by KristofferC** [comment]
I have thought the same. The reason it was put there was to keep compatibility with CALFEM. 

However, let's just get rid of it and document it.

I will make the PR.


One reason it could be there is if one wants to have a subset of elements that are not numbered 1, 2, ... n.
