### ISSUE TITLE
Separate CALFEM stuff into its own repo

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#53]
It's annoying to have all the CALFEM stuff in the same repo as the other new stuff. I suggest moving all the CALFEM stuff to its own repo, `CALFEM.jl` perhaps, and just let that one use `JuAFEM` like it does now. This would make it easier to keep the examples using the new JuAFEM stuff and the CALFEM stuff separate.

**Comment by fredrikekre** [comment]
So basically extracting the CALFEM API from `JuAFEM`? I'm up for it!
Would be nice to keep some standard elements somehow though, but then they don't have to be CALFEM compatible, but instead based on the `ContMechTensors.jl` and FEValues maybe?

**Comment by KristofferC** [comment]
Yes, extracting all the CALFEM stuff in a separate repo. Then all CALFEM documentation and stuff can go there. 

I don't see a reason to "keep" standard elements. The CALFEM elements are still there and are usable, just in another repo. The problem with "standard elements" is that they make quite a lot of assumptions on how they will be used and as soon as you break the assumption, they are pretty much useless.

In my view, the CALFEM stuff is basically for people who want to run simple analysis on solids and heat without learning much FEM, like in FEM - Solids. 
JuAFEM will be for people who want to create their own FE codes for which any "standard" stuff are insufficient.

By the way, it would be cool to have an example notebook solving the a problem similar to the incompressibility problem in FEM Solids. I guess one would make two FE Values with different quadratures and use one for the displacements and one for the pressures.

**Comment by fredrikekre** [comment]
Ok!

I guess I can remake my solution of the pressure problem using `FEValues` and upload it :)

**Comment by KristofferC** [comment]
Blam: https://github.com/KristofferC/CALFEM.jl
