### ISSUE TITLE
Change Square + Triangle -> Cube and Tetraheder

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#57]
Or something else. Ideas @fredrikekre?

**Comment by fredrikekre** [comment]
Yes, I like that :+1:

Makes more sense to talk about a 2D cube than a 3D square :)

**Comment by KristofferC** [comment]
Should the be called like `RefCube` to highlight that this is not any Cube but a reference cube with vertices at (-1,-1).. etc?

**Comment by fredrikekre** [comment]
Yea maybe, and change `Shape` to `RefShape` in `geometry_types.jl`?

**Comment by KristofferC** [comment]
Yes
