### ISSUE TITLE
Computing things on faces of elements

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#66]
There is no easy way right now to compute stuff needed for, e.g. surface traction. dealii has a `FEFaceValues` https://dealii.org/8.4.0/doxygen/deal.II/classFEFaceValues.html which has a `reinit!` method that takes a cell and a face number.

Not sure how this is done best.

**Comment by fredrikekre** [comment]
What does a `FEFaceValues` do that a regular `FEValues` cannot? For a 2D mesh, wouldn't it be possible to set up a regular `FEValues` but for a line instead and use for the boundary?

**Comment by KristofferC** [comment]
You then need to project your 2d coordinates to a 1d line, compute things there and then go back to your global coordinate system. 

Probably easier is just to map the local quadrature points of the line to the edge of the triangle and do the computation for the non zero shape functions at those points.
