### ISSUE TITLE
Distinction between geometric interpolation space and function interpolation space

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/JuAFEM.jl#79]
Since #71 this is not so clear IMO. Call the geometric interpolation functions for shape functions (since they are connected to the *shape*, e.g. geometry) and the function interpolation functions for base functions (they are the *base* for the FE-approximation)

This would probably mean that some current functions have to be renamed, e.g.

```jl
shape_value -> base_value
shape_gradient -> base_gradient
...
```

**Comment by KristofferC** [comment]
All the references I find says that shape functions interpolate the *solution*. When do you ever need to know the value of the "shape functions" for the geometry?

**Comment by fredrikekre** [comment]
I guess never...
Was just thinking about it when adding the spatial_coordinate
for instance [here](https://github.com/KristofferC/JuAFEM.jl/blob/master/src/commons_abstract_fevalues.jl#L90) what these functions should be called, but since they are only used internally maybe it doesnt really matter.
