### ISSUE TITLE
Change FEBoundaryValues

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/JuAFEM.jl#87]
For a 3D case, the `FEBoundaryValues` should be a 2D space, embedded in a 3D space. Like dealii has a `dim` and a `spacedim`.

**Comment by fredrikekre** [comment]
Skip this?

**Comment by KristofferC** [comment]
For now maybe yes.

**Comment by fredrikekre** [comment]
I don't think this is needed, the current solution is pretty nice.
