### ISSUE TITLE
Code duplications

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#90]
The code for `reinit!` for FEBoundaryValues is very similar to the one for FECellValues. Just need to set the active boundary and then the rest is the same so should be able to pull it out to a common function.

**Comment by fredrikekre** [comment]
https://github.com/KristofferC/JuAFEM.jl/blob/master/src/fe_boundary_values.jl#L120

Then we have to overload `det` here instead of having `detJ_boundary`

**Comment by KristofferC** [comment]
Maybe not worth it. Les leave it for now then.

**Comment by fredrikekre** [comment]
Well, its an easy think to fix.
